[mgr]
show_symlink = true
show_hidden = true

[opener]
play = [
	{ run = 'vlc "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = '"$EDITOR" "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
image = [
	{ run = 'eog "$@"', orphan = true, for = "unix" },
]

[open]
prepend_rules = [
	# open images with eog
	{ name = "*.png", use = "image" },
	{ name = "*.jpg", use = "image" },
	{ name = "*.jpeg", use = "image" },
	{ name = "*.gif", use = "image" },
	{ name = "*.bmp", use = "image" },
	{ name = "*.webp", use = "image" },
	{ name = "*.svg", use = "image" },
	{ name = "*.tiff", use = "image" },
	{ name = "*.tif", use = "image" },
	{ name = "*.ico", use = "image" },
	# open videos with vlc
	{ name = "*.mp4", use = "play" },
	{ name = "*.mkv", use = "play" },
	{ name = "*.avi", use = "play" },
	{ name = "*.mov", use = "play" },
	{ name = "*.wmv", use = "play" },
	{ name = "*.flv", use = "play" },
	{ name = "*.webm", use = "play" },
	{ name = "*.m4v", use = "play" },
	{ name = "*.mpeg", use = "play" },
	{ name = "*.mpg", use = "play" },
	{ name = "*.3gp", use = "play" },
	{ name = "*.ogv", use = "play" },
	{ name = "*.json", use = "edit" },
	{ name = "*.sh", use = "edit" },
	{ name = "*.toml", use = "edit" },
	{ name = "*.y*ml", use = "edit" },
	{ name = "*config", use = "edit" },
	{ name = "*.cfg", use = "edit" },
	{ name = "*env", use = "edit" },
	{ name = "*.d", use = "edit" },
	{ name = "*.md", use = "edit" },
	{ name = "*.txt", use = "edit" },
	{ name = ".zsh*", use = "edit" },
	{ name = "*.ini", use = "edit" },
	{ name = "*.lua", use = "edit" },
	{ name = "*.xml", use = "edit" },
	{ name = "*.log", use = "edit" },
# open with normal / gnome / kde
	{ name = "*.ods", use = "open" },
	{ name = "*.pdf", use = "open" },
# open with multimedia player
	{ name = "*.mp3", use = "play" },

]
append_rules = [
	{ name = "*", use = "edit" },
]
